SRC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payroll/', include('payroll.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payroll/urls.py
from django.urls import path, re_path
from .views import *

app_name= 'payroll'

urlpatterns = [
    path('', payslip_month, name = 'payslip_month'),
    path('emplyee_detail/<int:payslip_month_id>', employee_detail, name = 'employee_detail'),
    path('update_employee_detail/<int:employee_id>', update_employee_detail, name = 'update_employee_detail'),
    path('delete_employee/<int:employee_id>', delete_employee, name = 'delete_employee'),
    path('view_slip/<int:employee_id>', view_slip, name = 'view_slip'),
]

payroll/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from datetime import datetime

class PayslipMonth(models.Model):
    payslip_month = models.CharField(max_length = 100, unique = True)

    def __str__(self):
        return str(self.payslip_month)


class EmployeeDetail(models.Model):
    payslip_month = models.ForeignKey(PayslipMonth, on_delete = models.CASCADE)
    employee_id = models.IntegerField()
    employee_name = models.CharField(max_length = 100)
    designation = models.CharField(max_length = 100)
    date_of_joining = models.CharField(max_length = 100)
    pay_period = models.CharField(max_length = 100)
    pay_date = models.CharField(max_length = 100)
    pan_number = models.CharField(max_length = 100)
    basic_salary = models.IntegerField()
    performance_allowance = models.IntegerField()
    bonus_allowance = models.IntegerField()
    account_number = models.IntegerField()
    ifsc_code = models.CharField(max_length = 100)

payroll/forms.py
from django import forms
from .models import *

class MonthForm(forms.ModelForm):
    class Meta:
        model = PayslipMonth
        fields = [
            "payslip_month",  
        ]


class EmployeeDetailForm(forms.ModelForm):
    class Meta:
        model = EmployeeDetail
        fields = '__all__'

class UpdateEmployeeDetailForm(forms.ModelForm):
    class Meta:
        model = EmployeeDetail
        fields = '__all__'

payroll/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import *
from django.http import Http404,HttpResponseRedirect, \
                        HttpResponse, HttpResponseForbidden
from django.urls import reverse
from .forms import *

def payslip_month(request):

    if request.method == 'POST':
        monthform = MonthForm(request.POST)
        if monthform.is_valid():
            monthform = MonthForm(request.POST)
            new_month = monthform.save()

            return HttpResponseRedirect(reverse('payroll:employee_detail',args=(new_month.id,)))

    monthform = MonthForm()

    context = {
        "monthform":monthform,
    }
    return render(request, 'payslip_month.html', context)


def employee_detail(request, payslip_month_id):

    payslip_months = PayslipMonth.objects.get(id = payslip_month_id)

    if request.method == 'POST':
        employeeform = EmployeeDetailForm(request.POST, instance=payslip_months)
        if employeeform.is_valid():
            employeeform = EmployeeDetailForm(request.POST)
            new_employee = employeeform.save()

    employeeform = EmployeeDetailForm(instance=payslip_months)

    employees = EmployeeDetail.objects.filter(payslip_month = payslip_months)

    context = {
        "employeeform":employeeform,
        "employees":employees,
    }
    return render(request, 'employee_detail.html', context)


def update_employee_detail(request, employee_id):
    """
    Update Employee
    """
    employee = EmployeeDetail.objects.get(id = employee_id)
    payslip_month_id = employee.payslip_month

    if request.method=='POST':
        form = UpdateEmployeeDetailForm(request.POST,request.FILES, instance=employee)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('payroll:employee_detail',args=(payslip_month_id.id,)))
    form = UpdateEmployeeDetailForm(instance=employee)

    context = {
        "form":form
    }
    return render(request, 'update_employee_detail.html', context)


def delete_employee(request, employee_id):
    """
    Delete Brochure
    """
    employee = EmployeeDetail.objects.get(id = employee_id)
    payslip_month_id = employee.payslip_month
    employee.delete()

    return HttpResponseRedirect(reverse('payroll:employee_detail',args=(payslip_month_id.id,)))


def view_slip(request, employee_id):

    employee = EmployeeDetail.objects.get(id = employee_id)
    payslip_month_id = employee.payslip_month.id

    employee_details = EmployeeDetail.objects.filter(id = employee_id)

    payslip_month = PayslipMonth.objects.filter(id = payslip_month_id)

    for employee_detail in employee_details:
        # print(employee_detail.basic_salary)
        dearness_allowance = employee_detail.basic_salary/100 * 10
        house_rent_allowance = employee_detail.basic_salary/100 * 8
        travelling_allowance = employee_detail.basic_salary/100 * 6
        food_allowance = employee_detail.basic_salary/100 * 5
        total_balance = employee_detail.basic_salary + employee_detail.performance_allowance + employee_detail.bonus_allowance + dearness_allowance + house_rent_allowance + travelling_allowance + food_allowance

    context = {
        "employee_details":employee_details,
        "payslip_month":payslip_month,
        "dearness_allowance":dearness_allowance,
        "house_rent_allowance":house_rent_allowance,
        "travelling_allowance":travelling_allowance,
        "food_allowance":food_allowance,
        "total_balance":total_balance
    }
    return render(request, 'view_slip.html', context)

payroll/templates/employee_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Payslip Month</title>
</head>
<body>
    <form method = 'POST'>
        {% csrf_token %}
        {{employeeform.as_p}}
        <input type="submit">
    </form>
    <br>
            <h1 class="p-1 mb-2 blue-gradient  text-black">Employee List :-</h1>
            <br>
            {% for employee in employees %}
                <li>
                    <a href="{% url 'payroll:update_employee_detail' employee.id %}" class="btn btn-primary">{{ employee.employee_name }}</a>
                    &nbsp;&nbsp;
                    <a href="{% url 'payroll:delete_employee' employee.id %}" class="btn btn-primary">Delete</a>
                    &nbsp;&nbsp;
                    <a href="{% url 'payroll:view_slip' employee.id %}" class="btn btn-primary">View Slip</a>
                    &nbsp;&nbsp;
                </li>
            {% endfor %}
</body>
</html>

payroll/templates/payslip_month.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Payslip Month</title>
</head>
<body>
    <form method = 'POST'>
        {% csrf_token %}
        {{monthform.as_p}}
        <input type="submit">
    </form>
</body>
</html>

payroll/templates/update_employee_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
            <h1>Employee Details</h1>
            <form method='POST' enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{ form.as_p }}
                <input type="submit">
            </form>
</body>
</html>

payroll/templates/view_slip.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        table {
            border-collapse: collapse;
        }
        
        table, td, th {
            border: 1px solid black;
        }
        tr.noBorder td {
            border: 0;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Salary Slip</title>
</head>
<body>
    <center><table style="width:70%;">
            <tr>
                <td>
                    <center><IMG SRC="/static/css/img/gktcs_new_logo.png" width="200"></center>
                </td>
                <td>    
                    GKTCS Innovations 
                    </br>
                    </br>
                    2nd floor, Sumansudha, Besides OM Hospital,
                    </br>
                    Aamchi colony, NDA Pashan Road, Bavdhan
                    </br>
                    Pune 411021, Maharashtra, India.
                    </br>
                    Contact Person-Mr. Surendra Panpaliya
                    </br>
                    Contact no.-9975072320
                    </br>
                    </br>
                    {% for slip in payslip_month %}
                        Payslip for the Month of {{ slip.payslip_month }}
                    {% endfor %}
                </td>
            </tr>
            {% for employee_detail in employee_details %}
            <tr class="noBorder">
                <td align="left">
                    Employee ID : {{ employee_detail.employee_id }}
                    </br>
                    </br>
                    Employee Name : {{ employee_detail.employee_name }}
                    </br>
                    </br>
                    Designation : {{ employee_detail.designation }}
                    </br>
                    </br>
                    DOJ : {{ employee_detail.date_of_joining }}
                </td>
                <td align="left">
                    Pay Period : {{ employee_detail.pay_period }}
                    </br>
                    </br>
                    Pay Date : {{ employee_detail.pay_date }}
                    </br>
                    </br>
                    PAN Number : {{ employee_detail.pan_number }}
                </td>
            </tr>
            <tr>
                <td align="left">
                    Basic Salary : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{ employee_detail.basic_salary }}
                    </br>
                    </br>
                    Dearness Allowance : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{ dearness_allowance }}
                    </br>
                    </br>
                    House Rent Allowance : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{ house_rent_allowance }}
                    </br>
                    </br>
                    Travelling Allowance : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{ travelling_allowance }}
                    </br>
                    </br>
                    Food Allowance : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;
                    {{ food_allowance }}
                    </br>
                    </br>
                    Performance Allowance : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    {{ employee_detail.performance_allowance }}
                    </br>
                    </br>
                    Bonus Allowance : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;
                    {{ employee_detail.bonus_allowance }}
                    </br>
                    </br>
                    Total Balance : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{ total_balance }}
                </td>
                <td align="left">
                    Deduction will be written this side
                </td>
            </tr>
            <tr>
                <td colspan="2" align="left">
                    Employee Bank Account No. : {{ employee_detail.account_number }}
                    </br>
                    </br>
                    IFSC Code : {{ employee_detail.ifsc_code }}
                </td>
            </tr>
            {% endfor %}
        </table>
        
    </br>
        Note : This is electronically generated Pay slip hence does not require any signature.
    </center>
</body>
</html>